name: CI (Merge)

on:
  push:
    branches: [ main ]
    paths-ignore:
    - 'docs/**'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Build image
      uses: dagger/dagger-for-github@v8.2.0
      with:
        version: "0.19.4"
        verb: call
        args: build

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Run pipeline
      uses: dagger/dagger-for-github@v8.2.0
      with:
        version: "0.19.4"
        verb: call
        args: test-with-coverage

  e2e-test:
    name: E2E Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Run pipeline
      uses: dagger/dagger-for-github@v8.2.0
      with:
        version: "0.19.4"
        verb: call
        args: e-2-e-test

  publish-examples:
    name: Publish Examples
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Run pipeline
      uses: dagger/dagger-for-github@v8.2.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_USER: ${{ github.actor }}
        REPOSITORY_PREFIX: ${{ github.repository }}/cuemodules/cuestomize-examples
      with:
        version: "0.19.4"
        verb: call
        args: publish-examples --username="$GITHUB_USER" --password=env:GITHUB_TOKEN --repositoryPrefix="$REPOSITORY_PREFIX"
